<?php
//Custom Layouts
$layouts = array(
		'header_21' => array(
				'name' => 'LightHouse Header Fullwidth Simple',
				'template' => '<p>[vc_row content_placement=\"middle\" row_type=\"compact\" row_delimiter=\"\" row_fixed=\"1\" hide_on_tablet=\"\" hide_on_mobile=\"\" hide_on_frontpage=\"\" css=\".vc_custom_1568468354168{padding-right: 0px !important;padding-left: 0px !important;}\"][vc_column width=\"1/4\" column_align=\"left\" icons_position=\"left\" column_type=\"center\"][trx_sc_layouts_logo][/vc_column][vc_column width=\"3/4\" column_align=\"center\" icons_position=\"left\" offset=\"vc_col-lg-6\"][trx_sc_layouts_menu location=\"none\" menu=\"main-menu\" animation_in=\"fadeInUpSmall\" animation_out=\"fadeOutDownSmall\" mobile_button=\"1\" mobile_menu=\"1\" hide_on_mobile=\"1\" burger=\"\" mobile=\"1\" stretch=\"\" mobile_hide=\"1\"][/vc_column][vc_column width=\"1/4\" column_align=\"right\" icons_position=\"left\" offset=\"vc_hidden-md vc_hidden-sm vc_hidden-xs\"][trx_sc_layouts_iconed_text icon=\"icon-icon_phone\" hide_on_tablet=\"\" hide_on_mobile=\"\" text1=\"(123) 456-78-90\" link=\"tel:(123) 456-78-90\"][trx_sc_button type=\"default\" color_style=\"dark\" new_window=\"\" icon_position=\"left\" hide_on_tablet=\"\" hide_on_mobile=\"\" link=\"http://lighthouse.ancorathemes.com/donations/\" title=\"donate\"][/vc_column][/vc_row][vc_row scheme=\"dark\" row_type=\"normal\" row_delimiter=\"\" row_fixed=\"\" hide_on_mobile=\"\" hide_on_frontpage=\"1\" css=\".vc_custom_1502442530482{background: #f7f7f7 url(http://lighthouse.ancorathemes.com/wp-content/uploads/2017/06/title_bg.jpg?id=416) !important;background-position: center !important;background-repeat: no-repeat !important;background-size: cover !important;}\"][vc_column column_align=\"center\" icons_position=\"left\"][vc_empty_space alter_height=\"large\" hide_on_mobile=\"\" css=\".vc_custom_1502442885520{margin-top: -1.2rem !important;}\"][trx_sc_content size=\"1_1\" number_position=\"br\" title_style=\"default\" title_align=\"default\" padding=\"none\"][trx_sc_layouts_title title=\"1\" meta=\"\" breadcrumbs=\"1\" use_featured_image=\"\" hide_on_tablet=\"\" hide_on_mobile=\"\" hide_on_frontpage=\"\" icon_type=\"fontawesome\" icon_fontawesome=\"\"][/trx_sc_content][vc_empty_space alter_height=\"large\" hide_on_mobile=\"\" css=\".vc_custom_1502442995483{margin-top: -1.3rem !important;}\"][/vc_column][/vc_row]</p>
',
				'meta' => array(
						'trx_addons_layout_type' => 'header',
						'trx_addons_options' => 'a:2:{s:11:"layout_type";s:6:"header";s:6:"margin";s:0:"";}',
						'panels_data' => 's:0:"";',
						'_wpb_shortcodes_custom_css' => '.vc_custom_1568468354168{padding-right: 0px !important;padding-left: 0px !important;}.vc_custom_1502442530482{background: #f7f7f7 url(http://lighthouse.ancorathemes.com/wp-content/uploads/2017/06/title_bg.jpg?id=416) !important;background-position: center !important;background-repeat: no-repeat !important;background-size: cover !important;}.vc_custom_1502442885520{margin-top: -1.2rem !important;}.vc_custom_1502442995483{margin-top: -1.3rem !important;}'
						)
				),
		'header_23' => array(
				'name' => 'LightHouse Header Short /2 rows/',
				'template' => '[vc_row row_type=\"narrow\" row_delimiter=\"\" row_fixed=\"\" hide_on_tablet=\"1\" hide_on_mobile=\"1\" hide_on_frontpage=\"\"][vc_column column_align=\"center\" icons_position=\"left\" column_type=\"center\"][trx_sc_content size=\"1_1\" number_position=\"br\" title_style=\"default\" title_align=\"default\" width=\"1_1\" padding=\"none\" width2=\"1_1\"][vc_row_inner equal_height=\"yes\" content_placement=\"middle\"][vc_column_inner width=\"1/3\" column_align=\"left\" icons_position=\"left\"][trx_sc_layouts_iconed_text icon=\"none\" hide_on_tablet=\"\" hide_on_mobile=\"\" icon_type=\"fontawesome\" icon_fontawesome=\"icon-home-2\" text1=\"123, New Lenox Chicago, IL 60606\"][/vc_column_inner][vc_column_inner width=\"2/3\" column_align=\"right\" icons_position=\"left\"][trx_sc_layouts_iconed_text icon=\"icon-icon_phone\" hide_on_tablet=\"\" hide_on_mobile=\"\" text1=\"(123) 456-78-90\" link=\"tel:(123) 456-78-90\"][trx_sc_layouts_login hide_on_tablet=\"\" hide_on_mobile=\"\"][/vc_column_inner][/vc_row_inner][/trx_sc_content][/vc_column][/vc_row][vc_row row_type=\"compact\" row_delimiter=\"\" row_fixed=\"1\" hide_on_tablet=\"\" hide_on_mobile=\"\" hide_on_frontpage=\"\"][vc_column icons_position=\"left\" column_type=\"center\"][trx_sc_content size=\"1_1\" number_position=\"br\" title_style=\"default\" title_align=\"default\" width=\"1_1\" padding=\"none\" width2=\"1_1\"][vc_row_inner equal_height=\"yes\" content_placement=\"middle\"][vc_column_inner width=\"1/3\" column_align=\"left\" icons_position=\"left\"][trx_sc_layouts_logo][/vc_column_inner][vc_column_inner width=\"2/3\" column_align=\"right\" icons_position=\"left\"][trx_sc_layouts_menu location=\"none\" menu=\"menu-2\" animation_in=\"fadeInUpSmall\" animation_out=\"fadeOutDownSmall\" mobile_button=\"1\" mobile_menu=\"1\" hide_on_mobile=\"1\" burger=\"\" mobile=\"1\" stretch=\"\" mobile_hide=\"1\"][trx_sc_button type=\"default\" color_style=\"dark\" icon_position=\"left\" hide_on_tablet=\"1\" hide_on_mobile=\"1\" link=\"/donations/\" title=\"donate\"][/vc_column_inner][/vc_row_inner][/trx_sc_content][/vc_column][/vc_row]',
				'meta' => array(
						'trx_addons_layout_type' => 'header',
						'trx_addons_options' => 'a:2:{s:11:"layout_type";s:6:"header";s:6:"margin";s:0:"";}',
						'panels_data' => 's:0:"";',
						)
				),
		'footer_376' => array(
				'name' => 'LightHouse Footer',
				'template' => '[vc_row row_type=\"normal\" row_delimiter=\"\" row_fixed=\"\" hide_on_mobile=\"\" hide_on_frontpage=\"\"][vc_column column_align=\"center\" icons_position=\"left\"][trx_sc_content size=\"1_1\" number_position=\"br\" title_style=\"default\"][vc_empty_space alter_height=\"small\" hide_on_mobile=\"\"][trx_widget_contacts columns=\"\" googlemap=\"\" socials=\"\" logo=\"377\"][/trx_widget_contacts][vc_wp_custommenu nav_menu=\"51\"][vc_empty_space hide_on_mobile=\"\" css=\".vc_custom_1502445913772{margin-top: -0.6rem !important;}\"][trx_widget_contacts columns=\"\" googlemap=\"\" socials=\"1\"][/trx_widget_contacts][/trx_sc_content][trx_sc_content size=\"1_3\" float=\"center\" number_position=\"br\" title_style=\"default\"][vc_empty_space hide_on_mobile=\"\" css=\".vc_custom_1502446162214{margin-top: -0.7rem !important;}\"][vc_wp_text]<strong style=\"font-weight: 400;\"><a href=\"https://themeforest.net/user/ancorathemes/portfolio\" target=\"_blank\" rel=\"noopener noreferrer\">Ancora Themes</a> &copy; {Y}. All rights reserved.</strong>[/vc_wp_text][/trx_sc_content][/vc_column][/vc_row]',
				'meta' => array(
						'trx_addons_layout_type' => 'footer',
						'trx_addons_options' => 'a:2:{s:11:"layout_type";s:6:"footer";s:6:"margin";s:0:"";}',
						'panels_data' => 's:0:"";',
						'_wpb_shortcodes_custom_css' => '.vc_custom_1502445913772{margin-top: -0.6rem !important;}.vc_custom_1502446162214{margin-top: -0.7rem !important;}'
						)
				),
		'custom_594' => array(
				'name' => 'Shop promo',
				'template' => '<p>[vc_row css=\".vc_custom_1502949855689{background-image: url(http://lighthouse.ancorathemes.com/wp-content/uploads/2017/08/shop_promo_bg.jpg?id=580) !important;background-position: center !important;background-repeat: no-repeat !important;background-size: cover !important;}\"][vc_column icons_position=\"left\"][vc_empty_space alter_height=\"large\" hide_on_mobile=\"\" css=\".vc_custom_1502950849849{margin-top: -0.8rem !important;}\"][vc_column_text]</p>
<p style=\"text-align: center;\"><span class=\"trx_addons_shop_promo_large\">Buy logo</span> <span class=\"trx_addons_shop_promo_italic\">t-shirt</span><br />
<span class=\"trx_addons_shop_promo_small\">to</span> <span class=\"trx_addons_shop_promo_large\">help children</span></p>
<p>[/vc_column_text][vc_empty_space alter_height=\"small\" hide_on_mobile=\"\" css=\".vc_custom_1502950878639{margin-top: 1rem !important;}\"][trx_sc_button type=\"default\" new_window=\"\" align=\"center\" icon_position=\"left\" hide_on_tablet=\"\" hide_on_mobile=\"\" link=\"http://lighthouse.ancorathemes.com/shop/\" title=\"buy now\"][vc_empty_space alter_height=\"large\" hide_on_mobile=\"\" css=\".vc_custom_1502950914273{margin-top: -1.15rem !important;}\"][/vc_column][/vc_row]</p>
',
				'meta' => array(
						'trx_addons_layout_type' => 'custom',
						'trx_addons_options' => 'a:2:{s:11:"layout_type";s:6:"custom";s:6:"margin";s:0:"";}',
						'panels_data' => 's:0:"";',
						'_wpb_shortcodes_custom_css' => '.vc_custom_1502949855689{background-image: url(http://lighthouse.ancorathemes.com/wp-content/uploads/2017/08/shop_promo_bg.jpg?id=580) !important;background-position: center !important;background-repeat: no-repeat !important;background-size: cover !important;}.vc_custom_1502950849849{margin-top: -0.8rem !important;}.vc_custom_1502950878639{margin-top: 1rem !important;}.vc_custom_1502950914273{margin-top: -1.15rem !important;}'
						)
				),
		'header_706' => array(
				'name' => 'LightHouse Header Short Over /2 rows/',
				'template' => '<p>[vc_row row_type=\"narrow\" row_delimiter=\"\" row_fixed=\"\" hide_on_tablet=\"1\" hide_on_mobile=\"1\" hide_on_frontpage=\"\" css=\".vc_custom_1503412492664{background-color: #212a3c !important;}\"][vc_column column_align=\"center\" icons_position=\"left\" column_type=\"center\"][trx_sc_content size=\"1_1\" number_position=\"br\" title_style=\"default\" title_align=\"default\" width=\"1_1\" padding=\"none\" width2=\"1_1\"][vc_row_inner equal_height=\"yes\" content_placement=\"middle\"][vc_column_inner width=\"1/3\" column_align=\"left\" icons_position=\"left\"][trx_sc_layouts_iconed_text icon=\"none\" hide_on_tablet=\"\" hide_on_mobile=\"\" icon_type=\"fontawesome\" icon_fontawesome=\"icon-home-2\" text1=\"123, New Lenox Chicago, IL 60606\"][/vc_column_inner][vc_column_inner width=\"2/3\" column_align=\"right\" icons_position=\"left\"][trx_sc_layouts_iconed_text icon=\"icon-icon_phone\" hide_on_tablet=\"\" hide_on_mobile=\"\" text1=\"(123) 456-78-90\" link=\"tel:(123) 456-78-90\"][trx_sc_layouts_login hide_on_tablet=\"\" hide_on_mobile=\"\"][/vc_column_inner][/vc_row_inner][/trx_sc_content][/vc_column][/vc_row][vc_row row_type=\"compact\" row_delimiter=\"\" row_fixed=\"1\" hide_on_tablet=\"\" hide_on_mobile=\"\" hide_on_frontpage=\"\" css=\".vc_custom_1503330946297{background-color: rgba(255,255,255,0) !important;*background-color: rgb(255,255,255) !important;}\"][vc_column icons_position=\"left\" column_type=\"center\"][trx_sc_content size=\"1_1\" number_position=\"br\" title_style=\"default\" title_align=\"default\" width=\"1_1\" padding=\"none\" width2=\"1_1\"][vc_row_inner equal_height=\"yes\" content_placement=\"middle\"][vc_column_inner width=\"1/3\" column_align=\"left\" icons_position=\"left\"][trx_sc_layouts_logo hide_on_tablet=\"\" hide_on_mobile=\"\" logo=\"707\"][/vc_column_inner][vc_column_inner width=\"2/3\" column_align=\"right\" icons_position=\"left\"][trx_sc_layouts_menu location=\"none\" menu=\"menu-2\" animation_in=\"fadeInUpSmall\" animation_out=\"fadeOutDownSmall\" mobile_button=\"1\" mobile_menu=\"1\" hide_on_mobile=\"1\" burger=\"\" mobile=\"1\" stretch=\"\" mobile_hide=\"1\"][trx_sc_button type=\"default\" color_style=\"dark\" new_window=\"\" icon_position=\"left\" hide_on_tablet=\"1\" hide_on_mobile=\"1\" link=\"http://lighthouse.ancorathemes.com/donations/\" title=\"donate\"][/vc_column_inner][/vc_row_inner][/trx_sc_content][/vc_column][/vc_row]</p>
',
				'meta' => array(
						'trx_addons_layout_type' => 'header',
						'trx_addons_options' => 'a:2:{s:11:"layout_type";s:6:"header";s:6:"margin";s:0:"";}',
						'panels_data' => 's:0:"";',
						'_wpb_shortcodes_custom_css' => '.vc_custom_1503412492664{background-color: #212a3c !important;}.vc_custom_1503330946297{background-color: rgba(255,255,255,0) !important;*background-color: rgb(255,255,255) !important;}'
						)
				),
		'header_1097' => array(
				'name' => 'LightHouse Header Fullwidth Simple 2',
				'template' => '<p>[vc_row content_placement=\"middle\" row_type=\"compact\" row_delimiter=\"\" row_fixed=\"1\" hide_on_tablet=\"\" hide_on_mobile=\"\" hide_on_frontpage=\"\" css=\".vc_custom_1568468456130{padding-right: 30px !important;padding-left: 30px !important;}\"][vc_column width=\"1/4\" column_align=\"left\" icons_position=\"left\" column_type=\"center\"][trx_sc_layouts_logo][/vc_column][vc_column width=\"3/4\" column_align=\"center\" icons_position=\"left\" offset=\"vc_col-lg-6\"][trx_sc_layouts_menu location=\"none\" menu=\"main-menu\" animation_in=\"fadeInUpSmall\" animation_out=\"fadeOutDownSmall\" mobile_button=\"1\" mobile_menu=\"1\" hide_on_mobile=\"1\" burger=\"\" mobile=\"1\" stretch=\"\" mobile_hide=\"1\"][/vc_column][vc_column width=\"1/4\" column_align=\"right\" icons_position=\"left\" offset=\"vc_hidden-md vc_hidden-sm vc_hidden-xs\"][trx_sc_layouts_iconed_text icon=\"icon-icon_phone\" hide_on_tablet=\"\" hide_on_mobile=\"\" text1=\"(123) 456-78-90\" link=\"tel:(123) 456-78-90\"][trx_sc_button type=\"default\" color_style=\"dark\" new_window=\"\" icon_position=\"left\" hide_on_tablet=\"\" hide_on_mobile=\"\" link=\"http://lighthouse.ancorathemes.com/donations/\" title=\"donate\"][/vc_column][/vc_row][vc_row scheme=\"dark\" row_type=\"normal\" row_delimiter=\"\" row_fixed=\"\" hide_on_mobile=\"\" hide_on_frontpage=\"1\" css=\".vc_custom_1502442530482{background: #f7f7f7 url(http://lighthouse.ancorathemes.com/wp-content/uploads/2017/06/title_bg.jpg?id=416) !important;background-position: center !important;background-repeat: no-repeat !important;background-size: cover !important;}\"][vc_column column_align=\"center\" icons_position=\"left\"][vc_empty_space alter_height=\"large\" hide_on_mobile=\"\" css=\".vc_custom_1502442885520{margin-top: -1.2rem !important;}\"][trx_sc_content size=\"1_1\" number_position=\"br\" title_style=\"default\" title_align=\"default\" padding=\"none\"][trx_sc_layouts_title title=\"1\" meta=\"\" breadcrumbs=\"1\" use_featured_image=\"\" hide_on_tablet=\"\" hide_on_mobile=\"\" hide_on_frontpage=\"\" icon_type=\"fontawesome\" icon_fontawesome=\"\"][/trx_sc_content][vc_empty_space alter_height=\"large\" hide_on_mobile=\"\" css=\".vc_custom_1502442995483{margin-top: -1.3rem !important;}\"][/vc_column][/vc_row]</p>
',
				'meta' => array(
						'trx_addons_layout_type' => 'header',
						'trx_addons_options' => 'a:2:{s:11:"layout_type";s:6:"header";s:6:"margin";s:0:"";}',
						'panels_data' => 's:0:"";',
						'_wpb_shortcodes_custom_css' => '.vc_custom_1568468456130{padding-right: 30px !important;padding-left: 30px !important;}.vc_custom_1502442530482{background: #f7f7f7 url(http://lighthouse.ancorathemes.com/wp-content/uploads/2017/06/title_bg.jpg?id=416) !important;background-position: center !important;background-repeat: no-repeat !important;background-size: cover !important;}.vc_custom_1502442885520{margin-top: -1.2rem !important;}.vc_custom_1502442995483{margin-top: -1.3rem !important;}'
						)
				)
		);
?>